/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaControlador;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author david
 */
public class jFVentanaBienvenido extends javax.swing.JFrame {

    private jFModificarContrasenia ventanaModificarContrasenia;
    private JLabel IconoBienvenida;
    private URL imageUrl;
    private String user;

    /**
     * Creates new form jFVentanaBienvenido
     */
    public jFVentanaBienvenido() {
        initComponents();
        // Centra la ventana en la pantalla
        Modelo.Metodos.centrarVentanaEnPantalla(this);
        ventanaModificarContrasenia = new jFModificarContrasenia(user);
        inicializarImagen();
    }

    public jFVentanaBienvenido(String user) {
        this.user = user;
        initComponents();
        textoBienvenida();
        // Centra la ventana en la pantalla
        Modelo.Metodos.centrarVentanaEnPantalla(this);
        ventanaModificarContrasenia = new jFModificarContrasenia(user);
        inicializarImagen();
    }

    private void inicializarImagen() {
        imageUrl = getClass().getResource("/UI/usuario.png");
        if (imageUrl != null) {
            ImageIcon imageIcon = new ImageIcon(imageUrl);
            IconoBienvenida.setIcon(imageIcon);
        } else {
            System.err.println("URL is null. Check the path to the image.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBienvenido = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoLogueado = new javax.swing.JLabel();
        jBCerrarSesion = new javax.swing.JButton();
        jBNuevoUsuario = new javax.swing.JButton();
        jBmodifyPass = new javax.swing.JButton();
        IconoBienvenido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMostrar = new javax.swing.JTextArea();
        jPTitulo = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jBCerrar = new javax.swing.JButton();
        jBMinimizar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFichero = new javax.swing.JMenu();
        jMAbrirFichero = new javax.swing.JMenuItem();
        jMGuardarFichero = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMCambiarColores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));
        setSize(new java.awt.Dimension(900, 700));

        jPBienvenido.setBackground(new java.awt.Color(4, 28, 45));
        jPBienvenido.setMaximumSize(new java.awt.Dimension(900, 660));
        jPBienvenido.setMinimumSize(new java.awt.Dimension(900, 660));
        jPBienvenido.setPreferredSize(new java.awt.Dimension(900, 660));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bienvenid@");

        textoLogueado.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        textoLogueado.setForeground(new java.awt.Color(255, 255, 255));

        jBCerrarSesion.setBackground(new java.awt.Color(204, 1, 1));
        jBCerrarSesion.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jBCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jBCerrarSesion.setText("Cerrar sesion");
        jBCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarSesionActionPerformed(evt);
            }
        });

        jBNuevoUsuario.setBackground(new java.awt.Color(0, 235, 255));
        jBNuevoUsuario.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jBNuevoUsuario.setForeground(new java.awt.Color(0, 51, 102));
        jBNuevoUsuario.setText("Nuevo Usuario");
        jBNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoUsuarioActionPerformed(evt);
            }
        });

        jBmodifyPass.setBackground(new java.awt.Color(0, 255, 0));
        jBmodifyPass.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jBmodifyPass.setForeground(new java.awt.Color(0, 51, 102));
        jBmodifyPass.setText("Modificar Contraseña");
        jBmodifyPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodifyPassActionPerformed(evt);
            }
        });

        IconoBienvenido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaControlador/usuario.png"))); // NOI18N

        jTMostrar.setColumns(20);
        jTMostrar.setRows(5);
        jTMostrar.setMaximumSize(new java.awt.Dimension(700, 600));
        jTMostrar.setMinimumSize(new java.awt.Dimension(700, 600));
        jTMostrar.setPreferredSize(new java.awt.Dimension(700, 600));
        jScrollPane1.setViewportView(jTMostrar);

        jPTitulo.setBackground(new java.awt.Color(0, 235, 255));
        jPTitulo.setPreferredSize(new java.awt.Dimension(900, 40));

        jLTitulo.setBackground(new java.awt.Color(102, 255, 255));
        jLTitulo.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(0, 51, 102));
        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setText("   LOGIN");
        jLTitulo.setMaximumSize(new java.awt.Dimension(115, 25));
        jLTitulo.setMinimumSize(new java.awt.Dimension(115, 25));
        jLTitulo.setPreferredSize(new java.awt.Dimension(115, 25));

        jBCerrar.setBackground(new java.awt.Color(0, 51, 102));
        jBCerrar.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jBCerrar.setForeground(new java.awt.Color(255, 0, 0));
        jBCerrar.setText("X");
        jBCerrar.setMaximumSize(new java.awt.Dimension(40, 40));
        jBCerrar.setMinimumSize(new java.awt.Dimension(40, 40));
        jBCerrar.setPreferredSize(new java.awt.Dimension(40, 40));
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });

        jBMinimizar.setBackground(new java.awt.Color(0, 51, 102));
        jBMinimizar.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jBMinimizar.setForeground(new java.awt.Color(0, 235, 255));
        jBMinimizar.setText("_");
        jBMinimizar.setMaximumSize(new java.awt.Dimension(40, 40));
        jBMinimizar.setMinimumSize(new java.awt.Dimension(40, 40));
        jBMinimizar.setPreferredSize(new java.awt.Dimension(40, 40));
        jBMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMinimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTituloLayout = new javax.swing.GroupLayout(jPTitulo);
        jPTitulo.setLayout(jPTituloLayout);
        jPTituloLayout.setHorizontalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTituloLayout.createSequentialGroup()
                .addComponent(jLTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPTituloLayout.setVerticalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTituloLayout.createSequentialGroup()
                .addGroup(jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPTituloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBLimpiar.setBackground(new java.awt.Color(0, 255, 0));
        jBLimpiar.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jBLimpiar.setForeground(new java.awt.Color(0, 51, 102));
        jBLimpiar.setText("Limpiar pantalla");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBienvenidoLayout = new javax.swing.GroupLayout(jPBienvenido);
        jPBienvenido.setLayout(jPBienvenidoLayout);
        jPBienvenidoLayout.setHorizontalGroup(
            jPBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBienvenidoLayout.createSequentialGroup()
                .addGroup(jPBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBienvenidoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoLogueado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jBNuevoUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBmodifyPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jBCerrarSesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBLimpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                    .addGroup(jPBienvenidoLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(IconoBienvenido)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1)
                .addGap(41, 41, 41))
            .addGroup(jPBienvenidoLayout.createSequentialGroup()
                .addComponent(jPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPBienvenidoLayout.setVerticalGroup(
            jPBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBienvenidoLayout.createSequentialGroup()
                .addComponent(jPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPBienvenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBienvenidoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(IconoBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoLogueado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jBNuevoUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jBmodifyPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jBLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jBCerrarSesion))
                    .addComponent(jScrollPane1))
                .addGap(36, 36, 36))
        );

        jMenuFichero.setText("File");

        jMAbrirFichero.setText("Abrir fichero");
        jMAbrirFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAbrirFicheroActionPerformed(evt);
            }
        });
        jMenuFichero.add(jMAbrirFichero);

        jMGuardarFichero.setText("Guardar fichero");
        jMGuardarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGuardarFicheroActionPerformed(evt);
            }
        });
        jMenuFichero.add(jMGuardarFichero);

        jMenuBar1.add(jMenuFichero);

        jMenuEditar.setText("Edit");

        jMCambiarColores.setText("Cambiar colores");
        jMenuEditar.add(jMCambiarColores);

        jMenuBar1.add(jMenuEditar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarSesionActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCerrarSesionActionPerformed

    private void jBNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoUsuarioActionPerformed
        JFrame ventana = new jFAgregarUsuario();
        ventana.setVisible(true);
        ventana.pack();
        this.dispose();
    }//GEN-LAST:event_jBNuevoUsuarioActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed

    private void jBMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMinimizarActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jBMinimizarActionPerformed

    private void jMAbrirFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAbrirFicheroActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Solo archivos de texto", "txt");
        fileChooser.setFileFilter(filter);
        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fileChooser.getSelectedFile();
            mostrarContenidoFichero(fichero);
        }
    }//GEN-LAST:event_jMAbrirFicheroActionPerformed

    private void jMGuardarFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGuardarFicheroActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File fichero = fileChooser.getSelectedFile();
            //con el metodo "endsWith" comprobamos que el texto a guardar acabe en .txt devolviendo un boolean
            if (!fichero.getName().endsWith(".txt")) {
                // si no finaliza con .txt se le añade
                fichero = new File(fichero.getParentFile(), fichero.getName() + ".txt");
            }
            guardarContenidoEnFichero(fichero);
        }
    }//GEN-LAST:event_jMGuardarFicheroActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        jTMostrar.setText("");
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBmodifyPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodifyPassActionPerformed
        ventanaModificarContrasenia.setVisible(true);
    }//GEN-LAST:event_jBmodifyPassActionPerformed

    private void mostrarContenidoFichero(File fichero) {
        try {
            BufferedReader br = new BufferedReader(new FileReader(fichero));
            String linea;
            jTMostrar.setText(""); // Limpiamos el JTextArea antes de cargar el nuevo contenido
            while ((linea = br.readLine()) != null) {
                jTMostrar.append(linea + "\n"); // Agregamos cada línea al JTextArea
            }
            br.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void guardarContenidoEnFichero(File fichero) {
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(fichero));
            bw.write(jTMostrar.getText()); // Escribimos el contenido del JTextArea en el fichero
            bw.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void textoBienvenida() {
        textoLogueado.setText("Usuario: " + user.toUpperCase());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFVentanaBienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFVentanaBienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFVentanaBienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFVentanaBienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFVentanaBienvenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoBienvenido;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBCerrarSesion;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBMinimizar;
    private javax.swing.JButton jBNuevoUsuario;
    private javax.swing.JButton jBmodifyPass;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMAbrirFichero;
    private javax.swing.JMenuItem jMCambiarColores;
    private javax.swing.JMenuItem jMGuardarFichero;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuFichero;
    private javax.swing.JPanel jPBienvenido;
    private javax.swing.JPanel jPTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTMostrar;
    private javax.swing.JLabel textoLogueado;
    // End of variables declaration//GEN-END:variables
}
