package VistaControlador;

import Modelo.*;
import java.net.URL;
import javax.swing.*;

/**
 *
 * @author David
 */
public class VentanaLogin extends javax.swing.JFrame {

    Usuario a = new Usuario();
    JFrame ventanaBienvenido = new jFVentanaBienvenido();
    JFrame ventenaAgregar = new jFAgregarUsuario();
    private URL imageUrl = ClassLoader.getSystemResource("/UI/fondo_passwd.png");


    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imageIcon = new ImageIcon(imageUrl);
        jL_imagen_login.setIcon(imageIcon);

        jLCrearCuentaNueva.setText("<html><u>Haz clic para crear una nueva cuenta<u><html>");
        // Centra la ventana en la pantalla
        Modelo.Metodos.centrarVentanaEnPantalla(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTitulo = new javax.swing.JPanel();
        jLLogin = new javax.swing.JLabel();
        jBMinimizar = new javax.swing.JButton();
        jBCerrar = new javax.swing.JButton();
        jPLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTusuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jCheckMostrar = new javax.swing.JCheckBox();
        botonLogin = new javax.swing.JButton();
        jLCrearCuentaNueva = new javax.swing.JLabel();
        jL_imagen_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(670, 420, 420, 420));
        setMinimumSize(new java.awt.Dimension(670, 420));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(670, 420));

        jPTitulo.setBackground(new java.awt.Color(102, 255, 255));

        jLLogin.setBackground(new java.awt.Color(0, 235, 255));
        jLLogin.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLLogin.setForeground(new java.awt.Color(0, 51, 102));
        jLLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLogin.setText("   LOGIN");
        jLLogin.setMaximumSize(new java.awt.Dimension(115, 25));
        jLLogin.setMinimumSize(new java.awt.Dimension(115, 25));
        jLLogin.setPreferredSize(new java.awt.Dimension(115, 25));

        jBMinimizar.setBackground(new java.awt.Color(0, 51, 102));
        jBMinimizar.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jBMinimizar.setForeground(new java.awt.Color(0, 235, 255));
        jBMinimizar.setText("_");
        jBMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMinimizarActionPerformed(evt);
            }
        });

        jBCerrar.setBackground(new java.awt.Color(0, 51, 102));
        jBCerrar.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jBCerrar.setForeground(new java.awt.Color(204, 0, 0));
        jBCerrar.setText("X");
        jBCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTituloLayout = new javax.swing.GroupLayout(jPTitulo);
        jPTitulo.setLayout(jPTituloLayout);
        jPTituloLayout.setHorizontalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTituloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPTituloLayout.setVerticalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPLogin.setBackground(new java.awt.Color(4, 28, 45));
        jPLogin.setMaximumSize(new java.awt.Dimension(350, 400));
        jPLogin.setMinimumSize(new java.awt.Dimension(350, 400));
        jPLogin.setPreferredSize(new java.awt.Dimension(350, 400));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Por favor, introduzca sus credenciales para acceder:");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        jTusuario.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jTusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTusuarioActionPerformed(evt);
            }
        });

        jPassword.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jCheckMostrar.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jCheckMostrar.setForeground(new java.awt.Color(255, 255, 255));
        jCheckMostrar.setText("Mostrar");
        jCheckMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckMostrarActionPerformed(evt);
            }
        });

        botonLogin.setBackground(new java.awt.Color(0, 235, 255));
        botonLogin.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        botonLogin.setForeground(new java.awt.Color(0, 51, 102));
        botonLogin.setText("Loguear");
        botonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLoginActionPerformed(evt);
            }
        });

        jLCrearCuentaNueva.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLCrearCuentaNueva.setForeground(new java.awt.Color(255, 255, 255));
        jLCrearCuentaNueva.setText("Haz clic para crear una nueva cuenta");
        jLCrearCuentaNueva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCrearCuentaNuevaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPLoginLayout = new javax.swing.GroupLayout(jPLogin);
        jPLogin.setLayout(jPLoginLayout);
        jPLoginLayout.setHorizontalGroup(
            jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoginLayout.createSequentialGroup()
                .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLoginLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCrearCuentaNueva)))
                    .addGroup(jPLoginLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPLoginLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(390, 390, 390))
        );
        jPLoginLayout.setVerticalGroup(
            jPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLoginLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckMostrar)
                .addGap(60, 60, 60)
                .addComponent(botonLogin)
                .addGap(21, 21, 21)
                .addComponent(jLCrearCuentaNueva)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jL_imagen_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaControlador/fondo_passwd.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jL_imagen_login, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_imagen_login, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLoginActionPerformed

//        jFVentanaBienvenido ventanaBienvenido = new jFVentanaBienvenido(jTusuario.getText());
//        if (a.comprobarUsuario(jTusuario.getText(), new String(jPassword.getPassword()))) {
//            ventanaBienvenido.setVisible(true);
//            ventanaBienvenido.pack();
////            textoLogueado.setText("El usuario " + jTusuario.getText() + " esta logueado");
//        } else {
//            JOptionPane.showMessageDialog(this, "ERROR, usuario incorrecto.");
//        }
        String usuario = jTusuario.getText();
        String contraseña = new String(jPassword.getPassword());

        if (usuario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El usuario no puede estar vacio.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (BBDD.loguearse(usuario, contraseña)) {
                jFVentanaBienvenido ventanaBienvenido = new jFVentanaBienvenido(jTusuario.getText());
                ventanaBienvenido.setVisible(true);
                ventanaBienvenido.pack();
            } else {
                JOptionPane.showMessageDialog(this, "ERROR, usuario incorrecto.");
            }
        }


    }//GEN-LAST:event_botonLoginActionPerformed

    private void jTusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTusuarioActionPerformed
        botonLoginActionPerformed(evt);
    }//GEN-LAST:event_jTusuarioActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        botonLoginActionPerformed(evt);
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jCheckMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckMostrarActionPerformed
        if (jCheckMostrar.isSelected()) {
            jPassword.setEchoChar((char) 0);
        } else {
            jPassword.setEchoChar('*');
        }    }//GEN-LAST:event_jCheckMostrarActionPerformed

    private void jLCrearCuentaNuevaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCrearCuentaNuevaMouseClicked

        ventenaAgregar.setVisible(true);
        ventenaAgregar.setLocationRelativeTo(this);
        ventenaAgregar.pack();
    }//GEN-LAST:event_jLCrearCuentaNuevaMouseClicked

    private void jBMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMinimizarActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jBMinimizarActionPerformed

    private void jBCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCerrarActionPerformed

//    private void guardar(Usuario user) {
//        if (BBDD.guardarUsuario(user)) {
//            JOptionPane.showMessageDialog(jFAgregarUsuario, "El usuario ha sido creado");
//            jFAgregarUsuario.setVisible(false);
//        } else {
//            JOptionPane.showMessageDialog(jFAgregarUsuario, "No se ha podido agregar al usuario.", "Error en la base de datos", JOptionPane.ERROR_MESSAGE);
//        }
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLogin;
    private javax.swing.JButton jBCerrar;
    private javax.swing.JButton jBMinimizar;
    private javax.swing.JCheckBox jCheckMostrar;
    private javax.swing.JLabel jLCrearCuentaNueva;
    private javax.swing.JLabel jLLogin;
    private javax.swing.JLabel jL_imagen_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPLogin;
    private javax.swing.JPanel jPTitulo;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTusuario;
    // End of variables declaration//GEN-END:variables
}
